In [1]:
import numpy as np

In [14]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
data * 10

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [16]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [17]:
data.shape

(4, 3)

In [18]:
data.dtype

dtype('int64')

In [20]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

data = np.array(data)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
data.ndim # dimension

1

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.empty((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
arr1 = np.array([1, 3, 34, 46, 45,75])

arr1.dtype

dtype('int64')

In [52]:
arr1.astype(float)

array([ 1.,  3., 34., 46., 45., 75.])

In [53]:
arr1

array([ 1,  3, 34, 46, 45, 75])

In [ ]:
int_array = np.arange(1,10)
int_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array(1/int_array)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [68]:
arr = np.arange(10)
arr

arr_slice = arr[5:8]
arr_slice

arr_slice[1]=10000
arr

array([    0,     1,     2,     3,     4,     5, 10000,     7,     8,
           9])

In [69]:
arr = np.arange(10)
arr

arr_slice = arr[:]
arr_slice

arr_slice[1]=10000
arr

array([    0, 10000,     2,     3,     4,     5,     6,     7,     8,
           9])

In [70]:
arr = np.arange(10)
arr

arr_slice = arr[5:8].copy()
arr_slice

arr_slice[1]=10000
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [77]:
names = np.array(['Bob', 'John', 'Will', 'Bob', 'Will', 'Joe'])
names

array(['Bob', 'John', 'Will', 'Bob', 'Will', 'Joe'], dtype='<U4')

In [ ]:
names == "Bob"

array([ True, False, False,  True, False, False])

In [82]:
data = np.array([[1, 2], [4, 7], [-5, 6], [12, 76], [-76, 0]])
data

array([[  1,   2],
       [  4,   7],
       [ -5,   6],
       [ 12,  76],
       [-76,   0]])

In [84]:
data[data<0]=0
data

array([[ 1,  2],
       [ 4,  7],
       [ 0,  6],
       [12, 76],
       [ 0,  0]])

In [88]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
rows = [0, 1, 2]
cols = [1, 0, 1]

print(arr[rows, cols])


[2 3 6]


In [ ]:
arr = np.arange(15).reshape(3, 5)

